import type { Question } from './game-types';

export const questions: Question[] = [
  // 💑 Couples & Relationships
  {
    id: 1,
    category: 'couples',
    question: 'What is the term for a couple who finish each other\'s sentences?',
    options: ['In sync', 'Codependent', 'Enmeshed', 'Soul mates'],
    correct: 0,
  },
  {
    id: 2,
    category: 'couples',
    question: 'Which love language involves giving gifts to show affection?',
    options: ['Words of affirmation', 'Acts of service', 'Receiving gifts', 'Physical touch'],
    correct: 2,
  },
  {
    id: 3,
    category: 'couples',
    question: 'What is the average length of a first date?',
    options: ['30 minutes', '1 hour', '2 hours', '3 hours'],
    correct: 1,
  },
  {
    id: 4,
    category: 'couples',
    question: 'Which country celebrates "Qixi Festival" — the Chinese Valentine\'s Day?',
    options: ['Japan', 'Korea', 'China', 'Thailand'],
    correct: 2,
  },
  {
    id: 5,
    category: 'couples',
    question: 'What does XOXO stand for in love messages?',
    options: ['Extra ordinary kisses', 'Hugs and kisses', 'Kisses and hugs', 'Love and kisses'],
    correct: 2,
  },
  {
    id: 6,
    category: 'couples',
    question: 'What\'s the traditional gift for a 50th wedding anniversary?',
    options: ['Silver', 'Diamond', 'Gold', 'Platinum'],
    correct: 2,
  },
  {
    id: 7,
    category: 'couples',
    question: 'Which psychologist developed the triangular theory of love with passion, intimacy, and commitment?',
    options: ['Sigmund Freud', 'Robert Sternberg', 'John Gottman', 'Abraham Maslow'],
    correct: 1,
  },
  {
    id: 8,
    category: 'couples',
    question: 'Couples who laugh together tend to have what kind of relationship?',
    options: ['More conflicts', 'Stronger bonds', 'Less intimacy', 'Shorter duration'],
    correct: 1,
  },
  {
    id: 9,
    category: 'couples',
    question: 'What\'s the term for butterflies in the stomach feeling at the start of a relationship?',
    options: ['Limerence', 'Infatuation', 'Attachment', 'Bonding'],
    correct: 1,
  },
  {
    id: 10,
    category: 'couples',
    question: 'Which flower is most associated with romantic love?',
    options: ['Tulip', 'Lily', 'Rose', 'Orchid'],
    correct: 2,
  },

  // 🧠 General Knowledge
  {
    id: 11,
    category: 'knowledge',
    question: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correct: 2,
  },
  {
    id: 12,
    category: 'knowledge',
    question: 'How many sides does a hexagon have?',
    options: ['5', '6', '7', '8'],
    correct: 1,
  },
  {
    id: 13,
    category: 'knowledge',
    question: 'What element has the chemical symbol "Au"?',
    options: ['Silver', 'Copper', 'Gold', 'Aluminum'],
    correct: 2,
  },
  {
    id: 14,
    category: 'knowledge',
    question: 'Who painted the Mona Lisa?',
    options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'],
    correct: 1,
  },
  {
    id: 15,
    category: 'knowledge',
    question: 'What is the largest planet in our solar system?',
    options: ['Saturn', 'Neptune', 'Uranus', 'Jupiter'],
    correct: 3,
  },
  {
    id: 16,
    category: 'knowledge',
    question: 'In which year did World War II end?',
    options: ['1943', '1944', '1945', '1946'],
    correct: 2,
  },
  {
    id: 17,
    category: 'knowledge',
    question: 'What is the speed of light in km/s (approximately)?',
    options: ['100,000', '200,000', '300,000', '400,000'],
    correct: 2,
  },
  {
    id: 18,
    category: 'knowledge',
    question: 'Which ocean is the largest?',
    options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correct: 3,
  },
  {
    id: 19,
    category: 'knowledge',
    question: 'How many bones are in the adult human body?',
    options: ['186', '206', '226', '246'],
    correct: 1,
  },
  {
    id: 20,
    category: 'knowledge',
    question: 'What is the smallest country in the world by area?',
    options: ['Monaco', 'San Marino', 'Vatican City', 'Liechtenstein'],
    correct: 2,
  },

  // 🎭 Fun & Quirky
  {
    id: 21,
    category: 'quirky',
    question: 'Which animal can sleep standing up AND lying down?',
    options: ['Giraffe', 'Horse', 'Elephant', 'Cow'],
    correct: 1,
  },
  {
    id: 22,
    category: 'quirky',
    question: 'What color is a polar bear\'s skin (under the fur)?',
    options: ['White', 'Pink', 'Yellow', 'Black'],
    correct: 3,
  },
  {
    id: 23,
    category: 'quirky',
    question: 'How many hearts does an octopus have?',
    options: ['1', '2', '3', '4'],
    correct: 2,
  },
  {
    id: 24,
    category: 'quirky',
    question: 'What was the first toy to be advertised on TV?',
    options: ['Barbie', 'Mr. Potato Head', 'G.I. Joe', 'Hot Wheels'],
    correct: 1,
  },
  {
    id: 25,
    category: 'quirky',
    question: 'What is the most-watched YouTube video of all time?',
    options: ['Gangnam Style', 'Baby Shark', 'Despacito', 'Shape of You'],
    correct: 1,
  },
  {
    id: 26,
    category: 'quirky',
    question: 'Which country invented pizza?',
    options: ['France', 'Greece', 'Italy', 'Spain'],
    correct: 2,
  },
  {
    id: 27,
    category: 'quirky',
    question: 'What does a snail look like without its shell?',
    options: ['Just slime', 'A slug', 'A worm', 'Naked snail'],
    correct: 1,
  },
  {
    id: 28,
    category: 'quirky',
    question: 'How long is a jiffy? (actual unit of time)',
    options: ['1 second', '1 millisecond', '1/100th of a second', '1 microsecond'],
    correct: 2,
  },
  {
    id: 29,
    category: 'quirky',
    question: 'What was the first emoji ever created?',
    options: ['😂', '❤️', '😊', '👍'],
    correct: 2,
  },
  {
    id: 30,
    category: 'quirky',
    question: 'How many times can a piece of paper be folded in half?',
    options: ['5', '7', '9', '12'],
    correct: 1,
  },
  {
    id: 31,
    category: 'quirky',
    question: 'What is the fear of long words called? (ironically)',
    options: ['Glossophobia', 'Sesquipedalophobia', 'Hippopotomonstrosesquippedaliophobia', 'Logophobia'],
    correct: 2,
  },
  {
    id: 32,
    category: 'couples',
    question: 'What percentage of people marry their first love?',
    options: ['5%', '15%', '25%', '35%'],
    correct: 2,
  },
  {
    id: 33,
    category: 'knowledge',
    question: 'What is the most spoken language in the world?',
    options: ['Spanish', 'English', 'Mandarin Chinese', 'Hindi'],
    correct: 2,
  },
  {
    id: 34,
    category: 'quirky',
    question: 'Which planet rotates in the opposite direction to most others?',
    options: ['Mars', 'Neptune', 'Venus', 'Mercury'],
    correct: 2,
  },
  {
    id: 35,
    category: 'couples',
    question: 'How long does it take to form a new habit according to research?',
    options: ['21 days', '40 days', '66 days', '90 days'],
    correct: 2,
  },
];

export function getRandomQuestion(usedIds: Set<number>): Question | null {
  const available = questions.filter(q => !usedIds.has(q.id));
  if (available.length === 0) return null;
  return available[Math.floor(Math.random() * available.length)];
}
